[tool.poetry]
name = "aquamatch"
version = "0.1.3"
description = "Python package and script to validate, model water quality parameters with remote sensing data"
authors = ["Felipe Sodré <felipe.b4rros@gmail.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/FelipeSBarros/aquamatch"
repository = "https://github.com/FelipeSBarros/aquamatch"
keywords = ["remote sensing", "water quality", "sentinel-2", "acolite"]
classifiers = [
    "Topic :: Scientific/Engineering :: GIS",
    "Intended Audience :: Science/Research",
]

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
geopandas = "^1.1.1"
pandas = "^2.3.3"
boto3 = "^1.40.42"
sentinelhub = "^3.11.2"
pystac-client = "^0.9.0"
rasterio = "^1.4.3"
shapely = "^2.1.2"
requests = "^2.32.5"
netcdf4 = "^1.7.4"
zarr = "^3.2.1"
xarray = ">=2024.1.0"
rioxarray = "^0.22.0"
dask = "^2026.3.0"
matplotlib = "^3.10.9"
openpyxl = "^3.1.5"
mgrs = "^1.5.4"
python-dotenv = "^1.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.3"